version: '3.8'

networks: 
    backend:

    frontend:

services:

    mongo:
        image: mongo
        
        restart: unless-stopped
        
        networks: 
            - backend

        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example

    mongo-express:
        image: mongo-express
        restart: unless-stopped

        networks:
            - backend

        depends_on: 
            - mongo

        ports:
            - 8002:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example

    notes:
        build: 
            context: .
            dockerfile: Dockerfile
            target: notes-dev

        environment: 
            - PORT=8001

        networks:
            - frontend

        ports: 
            - 8001:8001

        volumes: 
            - ./src/apps/notes/:/app/

        working_dir: /app
        entrypoint: ["npm", "run", "start"]

    backend:
        build: 
            context: .
            dockerfile: Dockerfile
            target: backend-dev

        depends_on: 
            - mongo
            - notes
            - mongo-express

        environment: 
            - PORT=8000
            - MONGO_USERNAME=root
            - MONGO_PASSWORD=example

        networks:
            - backend

        ports: 
            - 8000:8000

        volumes: 
            - .:/app/

        working_dir: /app
        entrypoint: ["pm2-runtime", "start", "dev.ecosystem.config.js"]